myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('online_store.urls')),
]

myproject/online_store/urls.py
from django.urls import path
from online_store import views
from .views import all_clients, orders_by_client, order_full, upload_images, upload_images1

# edit_good,

app_name = 'online_store'

urlpatterns = [
    path('', all_clients, name="all_clients"),
    path('main/', views.main, name='main'),
    path('clients/', views.get_clients, name='clients'),
    path('goods/', views.get_goods, name='goods'),
    path('orders/', views.get_orders, name='orders'),
    path('client_orders/<int:client_id>', views.get_orders_by_client_id, name='client_orders'),
    path('delete_client/<int:client_id>', views.delete_client, name='delete_client'),
    path('delete_goods/<int:goods_id>', views.delete_goods, name='delete_goods'),
    path('delete_order/<int:order_id>', views.delete_order, name='delete_order'),
    path('edit_order_goods_id/<int:order_id>/<int:goods_id>', views.edit_order_goods_id, name='edit_order_goods_id'),
    path('client_goods/', views.client_goods, name='client_goods'),
    path("edit/", views.get_edit_good, name="get_edit_good"),
    path("order/<int:order_pk>", order_full, name="order_full"),

]

myproject/templates/base.html
<{% load static %}>
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}
            Электронный магазин
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
        <link rel="stylesheet" type="text/css" href="../static/css/styles.css">
    {% endblock %}
</head>
<body>
<header class="header">
    {% block header %}

        <div class="navbar">
            <nav class="nav">
                {% now "l d M Y" %}
                {% include 'inc_menu.html' %}
            </nav>
        </div>

    {% endblock %}
</header>
<div class="main container">
{% block h1 %}
    <h1>Главная страница</h1>
{% endblock h1 %}

    {% block main %}

        <p class="pub">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias numquam ipsum enim, neque
            nulla
            rerum voluptatum temporibus a! Enim veritatis, odio quasi molestiae rerum repellat dolore illo. Distinctio,
            praesentium maxime?</p>
        <h2>Добро пожаловать на сайт</h2>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Magnam voluptatibus, accusamus expedita voluptate
            illo,
            sint minus optio consectetur possimus, repellendus laborum eum voluptatum qui porro praesentium voluptatem
            cupiditate dolore ut?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus delectus ut quod mollitia tempora est
            atque
            dicta ipsum deleniti magnam quisquam, rem commodi cumque, perspiciatis rerum recusandae sit debitis
            dolorum!</p>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Consequatur repudiandae voluptatibus quisquam
            excepturi, aliquid dicta eius, voluptate alias recusandae maxime reiciendis reprehenderit nisi? Sed
            doloremque
            ullam cupiditate adipisci dignissimos ab?</p>

    {% endblock %}
</div>
<footer class="footer">
    {% block footer %}

        <small>
            <address>
                <a href="mailto:admin5588@mail.ru">admin5588@mail.ru</a>
                <a href="tel:749578566321">+749578566321</a>
            </address>
            &copy; TiVi_ov
            {% now "Y" %}
        </small>

    {% endblock %}
</footer>
</body>
</html>

myproject/templates/inc_menu.html
{% with request.resolver_match.url_name as url_name %}
    <ul>
        <li><a href="{% url 'online_store:main' %}" class="{% if url_name == 'home' %}active{% endif %}">
            Главная
        </a></li>
        <li><a href="{% url 'online_store:clients' %}" class="{% if url_name == 'client' %}active{% endif %}">
            Клиенты
        </a></li>
        <li><a href="{% url 'online_store:goods' %}" class="{% if url_name == 'goods' %}active{% endif %}">
            Покупка продуктов
        </a></li>
        <li><a href="{% url 'online_store:client_goods' %}" class="{% if url_name == 'client_goods' %}active{% endif %}">
            Заказы клиентов за время
        </a></li>
        <li><a href="{% url 'online_store:orders' %}" class="{% if url_name == 'orders' %}active{% endif %}">
            Все зказы клиентов
        </a></li>


    </ul>
{% endwith %}